# Generated by Django 4.1.1 on 2022-10-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_warehouse_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='warehouse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
