# Generated by Django 4.1.1 on 2022-11-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_interested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('eid', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Empsin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin', models.CharField(max_length=500)),
                ('salary', models.CharField(max_length=500)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
    ]
