# Generated by Django 4.1.1 on 2022-11-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_employee_alter_order_status_date_empsin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empsin',
            name='eid',
            field=models.CharField(max_length=500),
        ),
    ]
